language: php

php:
  - 7.2

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
          env: SYMFONY_VERSION=2.3.*
        - php: 7.2
          env: SYMFONY_VERSION=2.6.*
        - php: 7.2
          env: SYMFONY_VERSION=2.7.*
        - php: 7.2
          env: SYMFONY_VERSION=2.8.*
        - php: 7.2
          env: SYMFONY_VERSION=3.0.*
        - php: 7.2
          env: SYMFONY_VERSION=3.1.*
        - php: 7.2
          env: SYMFONY_VERSION=3.2.*
        - php: 7.2
          env: SYMFONY_VERSION=3.3.*
        - php: 7.2
          env: SYMFONY_VERSION=3.4.*
        - php: 7.2
          env: SYMFONY_VERSION=4.0.*
        - php: 7.2
          env: SYMFONY_VERSION=4.1.*
        - php: 7.2
          env: SYMFONY_VERSION=4.2.*
        - php: 7.2
          env: SYMFONY_VERSION=4.3.*
        - php: 7.2
          env: SYMFONY_VERSION=4.4.*
        - php: 7.2
          env: SYMFONY_VERSION=5.0.*
    allow_failures:
        - php: 5.6

before_install:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
